# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ToolBelt_4.0' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  	pod 'Alamofire', '~> 3.0'
 	pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'JSQMessagesViewController'
    pod 'Backendless'
    pod 'HTPressableButton'

end
